### ISSUE TITLE
Facebook oAuth Token Extension

### ISSUE THREAD

**Issue by MrJack91** [DMKEBUSINESSGMBH/typo3-t3socials#2]
Hi there

Very nice extension. Thanks you much.

I've got problems/questions for the facebook network.

**publish on fb page**
Is it possible to publish on fb page, instead of user timeline?

**token extension**
Are FB tokens automatically extended before they are invalid after 60 days?

**generic solution for auto publishing changes if entries will be created in frontend**
Is there a solution to automatic publish messages, if they are created in frontend (without calling the tx_t3socials_hooks_TCEHook)?

**facebook error**
With one specific account, when I choose connect the account, after the login there will be shown a facebook error: something went wrong.. (in german: "Leider ist etwas schief gelaufen. Wir arbeiten daran, dieses Problem so schnell wie möglich zu beheben.")
**-> solved:** some of the requested permissions are not valid, they are renamed. it will work if you ask for the publish_actions permissions in Hybrid_Providers_Facebook.

**btw: only for your information**
In Typo3 4.5 there are problems with...
- the hooks in util/tx_t3socials_util_Link->getRealUrlAbsUrlForLink(). The simulatestatic extension will break.
- util/tx_t3socials_util_Message->addMessage. tx_rnbase_util_Typo3Classes::getFlashMessageQueueClass will not work. t3lib_FlashMessageQueue::addMessage($message); does.
- manual publishing after save of new news entry (by click on the flash message) will display an error.

Best thanks for reading and your work.

Michael

**Comment by digedag** [comment]
> Is there a solution to automatic publish messages, if they are created in frontend (without calling the tx_t3socials_hooks_TCEHook)?

To answer you this question: there is no automatic process, but you can easily trigger an event with this code:

```
    $networkSrv = tx_t3socials_srv_ServiceRegistry::getNetworkService();
    $states = $networkSrv->exeuteAutoSend($table, $uid);
```

**Comment by digedag** [comment]
Another point:

> util/tx_t3socials_util_Message->addMessage.
> tx_rnbase_util_Typo3Classes::getFlashMessageQueueClass will not work. 

There was a bug in rn_base [that was fixed last week](https://github.com/digedag/rn_base/commit/1e74ddf4d23b076366f65c893a134058246b2128). It should be related. I will check this!

**Comment by MrJack91** [comment]
Thanks @digedag!
Does "DMK E-BUSINESS GmbH" currently using this extension with facebook? I'm thinking facebook api is too old and needs an update (incl hybridAuth).
Twitter and also the great architecture of this extension is working fine so far.

I ask because i have to give this functionality to a customer. Maybe I will extend the extension. Is the best solution i found.

**Comment by digedag** [comment]
I think @rengaw83 can answer your questions about facebook tomorrow. I'm not involved there...

**Comment by hannesbochmann** [comment]
> publish on fb page
> Is it possible to publish on fb page, instead of user timeline?

No this is not possible at the moment. This is because Hybrid_Providers_Facebook::setUserStatus. You would have to provide an own provider/connection (unfortunately this is not well documented in the moment) to post somewhere else than the timeline. (@see http://hybridauth.sourceforge.net/userguide/tuts/advanced-access-facebook-api.html)
With a new version of HybridAuth (see below) this seems to be possible. But than it would be necessary to configure the desired page ID and pass that along. The extension would need to be extended by that option.

> token extension
> Are FB tokens automatically extended before they are invalid after 60 days?

It seems like the HybridAuth library takes care of that. (search in the extension for setExtendedAccessToken than you will see the responsible calls)

> facebook error
> With one specific account, when I choose connect the account, after the login there will be shown a facebook error: something went wrong.. (in german: "Leider ist etwas schief gelaufen. Wir arbeiten daran, dieses Problem so schnell wie möglich zu beheben.")
> -> solved: some of the requested permissions are not valid, they are renamed. it will work if you ask for the publish_actions permissions in Hybrid_Providers_Facebook.

I think this would be fixed with the new HybridAuth version. (see below)

> the hooks in util/tx_t3socials_util_Link->getRealUrlAbsUrlForLink(). The simulatestatic extension will break.

Can you specify what's exactly the problem?

> manual publishing after save of new news entry (by click on the flash message) will display an error.

What error is displayed?

> Does "DMK E-BUSINESS GmbH" currently using this extension with facebook? I'm thinking facebook api is too old and needs an update (incl hybridAuth). 

At the moment we don't use this extension with facebook. So it's absolutely possible that the HybridAuth API is outdated. The extension uses currently version 2.1.2, but the newest version is 2.6.0. Can you replace t3socials/lib/hybridauth with the newest version and check if this fixes it. If so, can you please provide a pull request with the new HybridAuth version? 
Maybe it would be a good idea for the future to make it possible to change the path to the HybridAuth library by configuration. This way users could use newer versions without having to wait for a new extension version.

**Comment by MrJack91** [comment]
Hey so much thanks for all your prompt and detailed answers.

@digedag 
I updated rn_base and t3socials to the current version from git.
Get still the error with invalid class (line number may be different):
`Fatal error: Call to undefined method t3lib_FlashMessage::addMessage() in /typo3conf/ext/t3socials/util/class.tx_t3socials_util_Message.php on line 107`

@hannesbochmann 

> the hooks in util/tx_t3socials_util_Link->getRealUrlAbsUrlForLink(). The simulatestatic extension will break.

This will occur if it auto-pushs messages via the news trigger:
`#1: PHP Catchable Fatal Error: Argument 2 passed to tx_simulatestatic::hookLinkDataPostProc() must be an instance of t3lib_TStemplate, null given in /typo3/sysext/simulatestatic/class.tx_simulatestatic.php line 131 
`
My quick fix is to skip the hook for simulatestatic extension.

> manual publishing after save of new news entry (by click on the flash message) will display an error.

`Fatal error: Call to a member function includeLLFile() on a non-object in /typo3conf/ext/t3socials/mod/index.php on line 24`
I know, the same code will work for using it directly as backend module. I'm not the pi_base expert, so is hard to me to fix this.

I want to try the update HybridAuth to version 2.6.0 on next Tuesday.

**Comment by hannesbochmann** [comment]
The problem with simulatestatic should be fixed with the current master. Can you please check?

The problem with the manual publishing should be fixed now, too. You will need rn_base in the current master to make it work. There is one problem left, which shouldn't effect you. Since TYPO3 7.6 the HTML Markup in the FlashMessage is escaped.

**Comment by MrJack91** [comment]
Great, all the things are working. Thank you very much.
Trying in the next days to migrate to current hybridAuth 1.6.

**In the current master there's an error:**
If you trigger a message, and then publish them via the flashmessage link, an error occured: "tx_t3socials_models_Message requires an message type."

It's a typo in https://github.com/DMKEBUSINESSGMBH/typo3-t3socials/blob/master/mod/handler/class.tx_t3socials_mod_handler_Trigger.php#L120:
getTriggerId() should be written with double g.

Should be:
`$type = $this->getTriggerConfig() ? $this->getTriggerConfig()->getTriggerId() : 'manually';`

Not:
`$type = $this->getTriggerConfig() ? $this->getTriggerConfig()->getTrigerId() : 'manually';`

Sadly i doesn't hear before of your library rn_base. Maybe i would like pi_base little bit more. ;)
But now with extbase all is fine.
